#ddev-generated
RUN mkdir -p /opt/fzf && cd /opt/fzf && git init && git remote add origin https://github.com/junegunn/fzf.git && git fetch --depth 1 origin 3dd42f5aa2d7fc6f508f2b21408730a8678c0a19 && git checkout FETCH_HEAD && /opt/fzf/install --all && cp /root/.fzf.bash /opt
